default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: embarca_back_end_test_development

test:
  <<: *default
  database: embarca_back_end_test_test

#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>

production:
  <<: *default
  database: embarca_back_end_test_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>